### PR TITLE
feat(nav): add breadcrumbs

### PR DESCRIPTION
**Pull request by hashrock**
This PR introduces a simple breadcrumb navigation. For now, it's only for Local. wdyt?

image

image

### CODE REVIEW

**Comment by kitsonk** [comment]
This is a great idea. I had been thinking about it too. What I was thinking though is that it would be good to move it to the header, to the right of the logo.

example_—_kview

Let me know if are interested in doing that. If not, I can use your PR as the base for that.

**Comment by hashrock** [comment]
Yeah! I'm interesting in implementing header breadcrumbs. I'll update this PR later

**Comment by hashrock** [comment]
@kitsonk 
Sorry for the delay! I've moved the UI to the header. I think you're working on other UI development, so for now, I'm keeping it local only to avoid conflicts

**Comment by kitsonk** [comment]
@hashrock I have added a couple features. I tried to rebase your PR with main, but I don't have permission to push an update.

**Comment by hashrock** [comment]
Hmm, I have "Allow edits and access to secrets by maintainers" turned on, but it's strange.
If there are any issues, feel free to close this PR and copy the changes to your branch.

**Comment by kitsonk** [comment]
Maybe because I tried a rebase with a `--force`. 🤔

**Pull request merged**
